# Generated by Django 3.0.7 on 2020-06-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bets',
        ),
        migrations.AddField(
            model_name='bet',
            name='profiles',
            field=models.ManyToManyField(to='WannaBet.Profile'),
        ),
        migrations.AddField(
            model_name='bet',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='id',
            field=models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Challange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('M', 'Money'), ('A', 'Activity'), ('G', 'Gift')], max_length=1)),
                ('descrition', models.TextField()),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WannaBet.Bet')),
            ],
        ),
    ]
