# Generated by Django 3.0.7 on 2020-06-30 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0002_auto_20200630_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
