# Generated by Django 3.0.7 on 2020-06-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0003_auto_20200630_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bet',
            name='profiles',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WannaBet.Event'),
        ),
    ]
