# Generated by Django 3.0.7 on 2020-07-01 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0006_auto_20200701_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
