# Generated by Django 3.0.7 on 2020-07-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0007_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='identity',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='bet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
