# Generated by Django 3.0.7 on 2020-07-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0009_auto_20200702_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='identity',
            new_name='identifier',
        ),
    ]
