# Generated by Django 3.0.7 on 2020-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0010_auto_20200702_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='identifier',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
