# Generated by Django 3.0.7 on 2020-07-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0011_auto_20200702_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='side',
            field=models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('D', 'Draw')], default='None', max_length=1),
        ),
        migrations.AlterField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_event', to='WannaBet.Event'),
        ),
        migrations.RemoveField(
            model_name='bet',
            name='members',
        ),
        migrations.AddField(
            model_name='bet',
            name='members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_member', to='WannaBet.Profile'),
        ),
        migrations.DeleteModel(
            name='Sides',
        ),
    ]
