# Generated by Django 3.0.7 on 2020-07-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0012_auto_20200702_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='members',
        ),
        migrations.AddField(
            model_name='bet',
            name='members',
            field=models.ManyToManyField(null=True, related_name='bet_member', to='WannaBet.Profile'),
        ),
    ]
