# Generated by Django 3.0.7 on 2020-07-02 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0014_auto_20200702_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='side',
        ),
        migrations.CreateModel(
            name='Sides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('D', 'Draw')], max_length=1)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_choices', to='WannaBet.Bet')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WannaBet.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='side',
            field=models.ManyToManyField(through='WannaBet.Sides', to='WannaBet.Profile'),
        ),
    ]
