# Generated by Django 3.0.7 on 2020-07-03 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WannaBet', '0015_auto_20200702_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='members',
            field=models.ManyToManyField(related_name='bet_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='side',
            field=models.ManyToManyField(related_name='side_to', through='WannaBet.Sides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sides',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
