# Generated by Django 3.0.7 on 2020-07-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0016_auto_20200703_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='members',
        ),
    ]
