# Generated by Django 3.0.7 on 2020-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0018_auto_20200703_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='event',
            field=models.ManyToManyField(related_name='for_event', to='WannaBet.Event'),
        ),
    ]
