# Generated by Django 3.0.7 on 2020-07-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0020_auto_20200703_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='identifier',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
