# Generated by Django 3.0.7 on 2020-07-03 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0021_bet_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
