# Generated by Django 3.0.7 on 2020-07-03 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0022_auto_20200703_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
