# Generated by Django 3.0.7 on 2020-07-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WannaBet', '0023_auto_20200703_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scores',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.TextField(blank=True),
        ),
    ]
